library(tidyverse)
library(ComplexHeatmap)
library(circlize)
library(Seurat)
library(fgsea)
library(msigdbr)
library(patchwork)
library(stringr)
library(cowplot)
library(org.Hs.eg.db) # Human gene database
library(viridis)
library(org.Mm.eg.db)
library(AnnotationDbi)
library(enrichplot)
library(clusterProfiler)

# ── Load Seurat objects ──────────────────────────────────────────────────────────────────────

# RDS files of Seurat objects for preprocessed PBMC 4K and Zeisel data, rows in same order as labels
pbmc <- readRDS("pbmc_preprocessed.rds")
zeisel <- readRDS("zeisel_preprocessed.rds")
# Replace with csv files containing the scFLAME labels for each dataset
pbmc$scflame <- read.csv("pbmc_scflame_labels.csv", row.names = 1)$cluster
zeisel$scflame <- read.csv("zeisel_scflame_labels.csv", row.names = 1)$cluster

# ── FIGURE B (figure A is later) ──────────────────────────────────────────────────────────────────────
# ── config ────────────────────────────────────────────────────────────────────
scores_path <- "pbmc_gene_ranked.csv" # List of all genes with their scores per cluster, generated by gene_scoring.py
top_n <- 5 # top upregulated genes per cluster

# Known marker genes for annotation
KNOWN_MARKERS <- c(
  # Cytotoxic NK
  NKG7 = "NK cell",
  GNLY = "NK cell",
  PRF1 = "NK cell",
  KLRF1 = "NK cell",
  FGFBP2 = "NK cell",
  KLRD1 = "NK cell",
  SPON2 = "NK cell",

  # Classical Monocytes
  LYZ = "Classical Mono",
  S100A8 = "Classical Mono",
  S100A9 = "Classical Mono",
  MNDA = "Classical Mono",
  S100A12 = "Classical Mono",
  TYROBP = "Classical Mono",
  CSTA = "Classical Mono",

  # Activated CD4 T
  TNFRSF4 = "CD4+ Memory T",
  CD40LG = "CD4+ Memory T",
  CCL20 = "CD4+ Memory T",
  ITGB1 = "CD4+ Memory T",
  IL32 = "CD4+ Memory T",
  IL7R = "CD4+ Memory T",

  # Naive / central memory T
  CCR7 = "Naive T cell",
  LEF1 = "Naive T cell",
  MAL = "Naive T cell",
  FHIT = "Naive T cell",
  LRRN3 = "Naive T cell",
  TRAC = "Naive T cell",

  # Cytotoxic / γδ T
  CCL5 = "CD8+ Effector Memory T",
  TRGC2 = "CD8+ Effector Memory T",
  KLRG1 = "CD8+ Effector Memory T",
  CST7 = "CD8+ Effector Memory T",
  GZMA = "CD8+ Effector Memory T",

  # DC
  CST3 = "DC",
  MYCL = "DC",
  SCN9A = "DC",
  CD74 = "DC",

  # CD16+ Monocyte
  LST1 = "CD16+ Mono",
  MS4A7 = "CD16+ Mono",

  # pDC
  LILRA4 = "pDC",
  IRF7 = "pDC",

  # B cells
  CD79A = "B cell",
  CD79B = "B cell",
  MS4A1 = "B cell",
  IGHD = "B cell",
  IGHM = "B cell",
  BANK1 = "B cell",
  VPREB3 = "B cell"
)

CELLTYPE_COLOURS <- c(
  "CD4+ Memory T" = "#4A90D9",
  "B cell" = "#E05A2B",
  "Classical Mono" = "#52A552",
  "NK cell" = "#9B6BB5",
  "CD8+ Effector Memory T" = "#E8A838",
  "DC" = "#D4636B",
  "pDC" = "#4DB6AC",
  "Naive T cell" = "#56B4E9",
  "CD16+ Mono" = "#D81B60",
  "Other" = "grey88"
)

# ── load and select top upregulated genes per cluster ─────────────────────────
df <- read_csv(scores_path, show_col_types = FALSE)

df_filtered <- df |>
  filter(
    !str_detect(gene, "^MT-|^MTRN"), # Mitochondrial
    !str_detect(gene, "^RPL|^RPS"), # Ribosomal proteins
    !str_detect(gene, "^AL|^AC|^LINC|^MIR|^SNORD"), # Non-coding RNAs / pseudogenes
    !str_detect(gene, "^HIST"), # Histones
    !str_detect(gene, "^RP11"), # RP11 loci
  )

# Identify the unique target genes that hit the top 5 slot in at least one cluster
target_genes_list <- df_filtered |>
  group_by(cluster_k) |>
  slice_max(score, n = top_n, with_ties = FALSE) |>
  ungroup() |>
  distinct(gene) |>
  pull(gene)

# 2. Determine the clean row sorting order based on where their score peaks
# Single step: top 5 per cluster, preserving cluster order, deduplicating.
row_order <- df_filtered |>
  group_by(cluster_k) |>
  slice_max(score, n = top_n, with_ties = FALSE) |>
  ungroup() |>
  arrange(as.numeric(as.character(cluster_k)), desc(score)) |> # C0, C1, C2...
  distinct(gene, .keep_all = TRUE) |> # deduplicate: first occurrence wins
  pull(gene)


# We filter the dataset for our selected genes
score_mat <- df_filtered |>
  filter(gene %in% target_genes_list) |>
  dplyr::select(gene, cluster_k, score) |>
  pivot_wider(names_from = cluster_k, values_from = score) |> # No values_fill = 0 artifact!
  column_to_rownames("gene") |>
  as.matrix()

# ensure column order is numeric cluster order
score_mat <- score_mat[, order(as.numeric(colnames(score_mat))), drop = FALSE]

# apply row order
score_mat <- score_mat[row_order[row_order %in% rownames(score_mat)], , drop = FALSE]

# ── annotations ───────────────────────────────────────────────────────────────
cell_type <- ifelse(
  rownames(score_mat) %in% names(KNOWN_MARKERS),
  KNOWN_MARKERS[rownames(score_mat)],
  "Other"
)

row_ann <- rowAnnotation(
  `Cell type` = cell_type,
  col = list(`Cell type` = CELLTYPE_COLOURS),
  simple_anno_size = unit(2, "mm"),
  annotation_name_gp = gpar(fontsize = 5.5, fontface = "bold"),
  annotation_name_side = "top",
  annotation_legend_param = list(
    `Cell type` = list(
      title_gp = gpar(fontsize = 5.8, fontface = "bold"),
      labels_gp = gpar(fontsize = 5.4),
      grid_height = unit(2, "mm"),
      grid_width = unit(2, "mm")
    )
  )
)

# ── colour scale ──────────────────────────────────────────────────────────────
col_fun <- colorRamp2(c(-1.5, 0, 1.5), c("#3B82C4", "white", "#C0392B"))

n_clusters <- ncol(score_mat)
n_genes <- nrow(score_mat)
ht_opt$TITLE_PADDING <- unit(1, "mm")

# ── heatmap ───────────────────────────────────────────────────────────────────
ht <- Heatmap(
  score_mat,
  name = "Gene score",
  col = col_fun,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = TRUE,
  column_labels = paste0("C", colnames(score_mat)),
  row_names_gp = gpar(
    fontsize = 5.4,
    fontface = ifelse(rownames(score_mat) %in% names(KNOWN_MARKERS),
      "bold.italic", "plain"
    )
  ),
  column_names_gp = gpar(fontsize = 5.4, fontface = "bold"),
  column_names_rot = 0,
  column_names_centered = TRUE,
  column_title = "Cluster",
  column_title_side = "bottom",
  column_title_gp = gpar(fontsize = 5.8, fontface = "bold"),
  row_title = NULL,
  right_annotation = row_ann,
  border = TRUE,
  border_gp = gpar(lwd = 0.6),
  row_gap = unit(0, "mm"),
  column_gap = unit(0, "mm"),
  width = unit(25, "mm"),
  height = unit(103, "mm"),
  heatmap_legend_param = list(
    title_gp      = gpar(fontsize = 5.8, fontface = "bold"),
    labels_gp     = gpar(fontsize = 5.5),
    legend_height = unit(18, "mm"),
    grid_width    = unit(2, "mm"),
    border        = "grey40"
  )
)


# ── save ──────────────────────────────────────────────────────────────────────
pdf("figure_b_heatmap.pdf",
  width = 2.8,
  height = 4.8
)
draw(ht, padding = unit(c(1, 1, 1, 1), "mm"))

dev.off()

message("Saved - figure_b_heatmap.pdf")

# ── FIGURE A ──────────────────────────────────────────────────────────────────────

DotPlot(
  object   = pbmc,
  features = row_order, # use row_order directly, already correctly ordered
  group.by = "scflame_new"
)

features <- target_genes_list

# ── Get dot plot data in the correct row order ─────────────────────────────
dot_data <- DotPlot(
  object   = pbmc,
  features = row_order,
  group.by = "scflame_new"
)$data

# Force gene factor levels to match heatmap row order
dot_data$features.plot <- factor(dot_data$features.plot, levels = rev(row_order))

# ── Build the dot plot ─────────────────────────────────────────────────────
dp <- ggplot(dot_data, aes(
  x = id,
  y = features.plot,
  size = pct.exp,
  color = avg.exp.scaled
)) +
  geom_point(shape = 16) +
  scale_size(range = c(0, 2), name = "% expressed") +
  scale_color_gradient(low = "grey90", high = "#88419F", name = "Avg expression") +
  scale_x_discrete(labels = paste0("C", levels(factor(dot_data$id)))) +
  scale_y_discrete(expand = c(0, 0.5)) +
  theme_bw(base_size = 6) +
  theme(
    axis.text.x = element_text(size = 5.4, colour = "black", face = "bold", angle = 0, hjust = 0.5),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title = element_blank(),
    panel.grid.major = element_line(colour = "white", linewidth = 0),
    panel.border = element_rect(colour = "black", linewidth = 0.5),
    legend.key.size = unit(3, "mm"),
    legend.text = element_text(size = 5.5),
    legend.title = element_text(size = 5.5, face = "bold"),
    legend.position = "left"
  ) +
  labs(x = "Cluster", y = NULL) +
  force_panelsizes(rows = unit(103.5, "mm"))


ggsave("figa_dotplot.pdf", dp, dpi = 300, width = 47, height = 119, units = "mm")

# ── FIGURE C and S17? check this ──────────────────────────────────────────────────────────────────────
input_ranked_csv <- "pbmc_gene_ranked.csv"

# ── load scores ───────────────────────────────────────────
df_ranked <- read_csv(input_ranked_csv, show_col_types = FALSE)

target_clusters <- c("0", "1", "2", "3", "4", "5", "6", "7")
top_n_paths <- 3

cluster_labels <- c(
  "0" = "C0: DC",
  "1" = "C1: CD8+ Effector Memory T",
  "2" = "C2: Classical Mono",
  "3" = "C3: B cells",
  "4" = "C4: Naive T cells",
  "5" = "C5: NK cells",
  "6" = "C6: CD4+ Memory T",
  "7" = "C7: CD16+ monocytes"
)

# ── Fetch MSigDB Pathways ──────────────────────────────────────────────────
message("Fetching MSigDB Pathways...")
m_df <- msigdbr(species = "Homo sapiens", category = "C7")
pathways_list <- split(m_df$gene_symbol, m_df$gs_name)

# ── Run FGSEA for Target Clusters ──────────────────────────────────────────
run_cluster_fgsea <- function(k, data, pathways) {
  cluster_data <- data |>
    filter(cluster_k == as.numeric(k)) |>
    arrange(desc(score))

  ranks <- setNames(cluster_data$score, cluster_data$gene)

  fgsea_res <- fgseaMultilevel(
    pathways = pathways, stats = ranks,
    minSize = 10, maxSize = 500, eps = 0
  )

  if (is.null(fgsea_res) || nrow(fgsea_res) == 0) {
    return(NULL)
  }
  fgsea_res |>
    as_tibble() |>
    mutate(cluster_k = as.character(k))
}

all_gsea_results <- map_dfr(c(0:7), ~ run_cluster_fgsea(.x, df_ranked, pathways_list))
all_res <- all_gsea_results

# ── Run with ClusterProfiler instead ──────────────────────────────────────────

run_cluster_gsea_cp <- function(k, data) {
  ranks <- data |>
    dplyr::filter(cluster_k == as.numeric(k)) |>
    dplyr::arrange(dplyr::desc(score)) |>
    (\(x) stats::setNames(x$score, x$gene))()

  term2gene <- m_df |>
    dplyr::select(gs_name, gene_symbol)

  clusterProfiler::GSEA(
    geneList      = ranks,
    TERM2GENE     = term2gene,
    minGSSize     = 10,
    maxGSSize     = 500,
    pvalueCutoff  = 1,
    eps           = 0,
    seed          = TRUE,
    pAdjustMethod = "BH"
  )
}

gsea_objects <- purrr::map(c(0:7), ~ run_cluster_gsea_cp(.x, df_ranked))
names(gsea_objects) <- target_clusters

plot_gsea_clean <- function(res, top_ids, title,
                            colors = c("#9970AB", "#D95F02", "#1B9E77")) {
  colors <- colors[seq_along(top_ids)]

  # ── Extract enrichment curve data ─────────────────────────────────────────
  gsdata <- do.call(rbind, lapply(seq_along(top_ids), function(i) {
    enrichplot:::gsInfo(res, top_ids[i]) |>
      mutate(pathway = top_ids[i], color = colors[i])
  }))

  # Shorten labels for legend
  label_map <- setNames(
    str_trunc(str_replace(top_ids, "GSE[0-9]+_", ""), 45, ellipsis = "…"),
    top_ids
  )
  gsdata$label <- label_map[gsdata$pathway]

  # ── Panel 1: Running ES curve ──────────────────────────────────────────────
  p1 <- ggplot(gsdata, aes(x = x, y = runningScore, colour = label)) +
    geom_hline(yintercept = 0, linewidth = 0.25, colour = "grey50", linetype = "dashed") +
    geom_line(linewidth = 0.4) +
    scale_colour_manual(values = setNames(colors, label_map[top_ids])) +
    scale_x_continuous(expand = c(0.01, 0)) +
    labs(x = NULL, y = "Running Enrichment Score", title = title, colour = NULL) +
    theme_classic(base_size = 5.8) +
    theme(
      plot.title = element_text(size = 5.8, face = "bold"),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.line.x = element_blank(),
      axis.title.y = element_text(size = 5.8),
      axis.text.y = element_text(size = 5.8),
      legend.position = c(1.03, 1.08),
      legend.justification = c(1, 1),
      legend.text = element_text(size = 5),
      legend.key.height = unit(1.5, "mm"),
      legend.key.width = unit(3, "mm"),
      legend.background = element_blank(),
      plot.margin = margin(2, 2, 0, 2)
    )

  # ── Panel 2: Barcode ───────────────────────────────────────────────────────
  # Each pathway gets its own horizontal strip
  n <- length(top_ids)
  barcode_data <- do.call(rbind, lapply(seq_along(top_ids), function(i) {
    d <- enrichplot:::gsInfo(res, top_ids[i])
    d |>
      filter(position == 1) |>
      mutate(
        pathway = top_ids[i],
        label   = label_map[top_ids[i]],
        ymin    = (i - 1) / n,
        ymax    = i / n - 0.05,
        color   = colors[i]
      )
  }))

  p2 <- ggplot(barcode_data, aes(
    x = x, xend = x,
    y = ymin, yend = ymax,
    colour = label
  )) +
    geom_segment(linewidth = 0.15) +
    scale_colour_manual(values = setNames(colors, label_map[top_ids])) +
    scale_x_continuous(expand = c(0.01, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(x = "Gene Rank", y = NULL) +
    theme_classic(base_size = 5.8) +
    theme(
      axis.text.y       = element_blank(),
      axis.ticks.y      = element_blank(),
      axis.line.y       = element_blank(),
      axis.text.x       = element_text(size = 5.5),
      axis.title.x      = element_text(size = 5.5),
      legend.position   = "none",
      plot.margin       = margin(0, 2, 2, 2)
    )

  # ── Combine with patchwork ─────────────────────────────────────────────────
  p1 / p2 + plot_layout(heights = c(4, 1))
}

# ── Apply to all clusters ──────────────────────────────────────────────────────
plots_clean <- imap(gsea_objects, function(res, k) {
  cluster_idx <- as.numeric(k)

  top_ids <- res@result |>
    filter(!str_detect(ID, "^HOEK")) |>
    filter(!str_detect(ID, "^KAZMIN")) |>
    filter(p.adjust < 0.05, NES > 0) |>
    arrange(p.adjust) |>
    slice_head(n = top_n_paths) |>
    pull(ID)

  if (length(top_ids) == 0) {
    message("No significant paths for cluster ", k)
    return(NULL)
  }

  plot_gsea_clean(res, top_ids, title = cluster_labels[cluster_idx + 1])
})


c0 <- plots_clean[1][[1]]
c3 <- plots_clean[4][[1]]
c4 <- plots_clean[5][[1]]

# This will force them into a clean grid regardless of internal panels
mountains <- plot_grid(c0, c3, c4, ncol = 1)

ggsave("FigC_mountains.pdf", mountains, width = 68, height = 123, units = "mm", dpi = 300)


gsea_summary <- all_res |>
  filter(NES > 0) |> # Keep only positive Normalized Enrichment Scores
  group_by(cluster_k) |> # Group by your cluster column
  arrange(pval, .by_group = TRUE) |> # Sort by significance (lowest p-value first) within each cluster
  slice_head(n = 10) |> # Take the top 10 rows for each cluster
  ungroup() |>
  dplyr::select(cluster_k, pathway, NES, pval, padj) # Pull out only the relevant metrics

# Print the entire combined summary table
print(gsea_summary, n = Inf)

df_out <- gsea_summary |>
  mutate(across(where(is.numeric), ~ signif(.x, 3)))
write.csv(df_out, "pbmc_pathways.csv", row.names = FALSE)


c0 <- plots_clean[2][[1]]
c2 <- plots_clean[3][[1]]
c4 <- plots_clean[6][[1]]
c6 <- plots_clean[7][[1]]
c7 <- plots_clean[8][[1]]

mountains_extra <- plot_grid(c0, c2, c4, c6, c7, ncol = 2)


ggsave("ExtraFigC_mountains.pdf", mountains_extra, width = 150, height = 150, units = "mm", dpi = 300)

# ── FIGURE S18a ──────────────────────────────────────────────────────────────────────

# Load top 100 genes per cluster
df <- read_csv("pbmc_gene_scores_top100.csv", show_col_types = FALSE)

cluster_labels <- c(
  "0" = "C0: DC",
  "1" = "C1: CD8+ Effector Memory T",
  "2" = "C2: Classical Mono",
  "3" = "C3: B cells",
  "4" = "C4: Naive T cells",
  "5" = "C5: NK cells",
  "6" = "C6: CD4+ Memory T",
  "7" = "C7: CD16+ monocytes"
)

# Run Pathway Enrichment
run_enrichment <- function(k, data) {
  # Get top 50 genes for this cluster
  genes <- data |>
    filter(cluster_k == k, score > 0) |>
    slice_max(score, n = 50) |>
    pull(gene)

  # Run Gene Ontology (Biological Process) enrichment
  res <- enrichGO(
    gene          = genes,
    OrgDb         = org.Hs.eg.db,
    keyType       = "SYMBOL",
    ont           = "BP", # Biological Process
    pAdjustMethod = "BH", # Benjamini-Hochberg FDR
    pvalueCutoff  = 0.05,
    qvalueCutoff  = 0.2
  )

  if (is.null(res) || nrow(res@result) == 0) {
    return(NULL)
  }

  # Add cluster ID to results
  res@result |> mutate(cluster_k = as.character(k))
}

# Apply across all clusters and combine
message("Running Pathway Enrichment... (This may take a minute)")
enrich_res <- map_dfr(names(cluster_labels), ~ run_enrichment(.x, df))


# Prepare data for plotting
plot_data <- enrich_res |>
  filter(p.adjust < 0.05) |> # Keep only significant pathways
  group_by(cluster_k) |>
  slice_min(p.adjust, n = 3, with_ties = FALSE) |> # Top 4 pathways per cluster
  ungroup() |>
  mutate(
    # Convert "10/50" GeneRatio string to a numeric decimal (0.2)
    GeneRatio_num = sapply(strsplit(GeneRatio, "/"), function(x) as.numeric(x[1]) / as.numeric(x[2])),
    # Calculate -log10(FDR)
    `-log10(FDR)` = -log10(p.adjust),
    # Map biological names to clusters
    Cluster_Name = cluster_labels[cluster_k],
    # Clean up overly long GO terms
    Description = str_wrap(Description, width = 45)
  ) |>
  # Order the y-axis pathways so they group nicely by cluster
  arrange(cluster_k, p.adjust) |>
  mutate(Description = factor(Description, levels = unique(Description)))

# Order the x-axis properly
plot_data$Cluster_Name <- factor(plot_data$Cluster_Name, levels = cluster_labels)
plot_data$Cluster_Name <- factor(plot_data$Cluster_Name,
  labels = paste0("C", seq_along(unique(plot_data$Cluster_Name)) - 1)
)

# Generate Dot Plot
p <- ggplot(plot_data, aes(x = Cluster_Name, y = Description)) +
  geom_point(aes(size = GeneRatio_num, fill = `-log10(FDR)`),
    shape = 21, stroke = 0.2, color = "black"
  ) +
  scale_fill_viridis(option = "plasma", direction = -1, name = expression(-log[10](FDR))) +
  scale_size_continuous(range = c(0.8, 2.8), name = "Gene Ratio") +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = 5.2, base_family = "Helvetica") +
  theme(
    axis.text.x = element_text(
      angle = 45, hjust = 1, vjust = 1, color = "black",
      face = "bold", size = 5.2
    ),
    axis.text.y = element_text(color = "black", size = 5.2),
    axis.title = element_text(size = 5.2),
    panel.grid.major.x = element_line(color = "grey90", linetype = "dashed", linewidth = 0.15),
    panel.grid.major.y = element_line(color = "grey90", linetype = "dotted", linewidth = 0.15),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.3),
    legend.position = "right",
    legend.title = element_text(face = "bold", size = 5.2),
    legend.text = element_text(size = 5.2),
    legend.key.size = unit(2.5, "mm"),
    legend.spacing.y = unit(0.5, "mm"),
    legend.box.spacing = unit(1, "mm"),
    plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "mm")
  )

ggsave("ORA_enrichment.pdf",
  plot = p,
  width = 75, height = 85, units = "mm", device = cairo_pdf
)

# ── FIGURE S18b ──────────────────────────────────────────────────────────────────────

# --- Load cluster difference files ---
c2 <- read_csv("pbmc_cluster_2_vs_7_top10_c2.csv") # Classical Monocyte side (negative)
c7 <- read_csv("pbmc_cluster_7_vs_2_top10_c7.csv") # DC/CD16+ Mono side (positive)

gene_col <- "gene"
score_col <- "score"
rank_col <- "rank"

genes_c2 <- c("S100A8", "S100A12", "S100A9") # Classical Monocyte side
genes_c7 <- c("FCGR3A", "CDKN1C", "RHOC") # DC/CD16+ Mono side

c2 <- c2 |>
  rename(gene = !!gene_col, score = !!score_col, rank = !!rank_col) |>
  filter(gene %in% genes_c2) |>
  mutate(
    cluster = "Classical monocyte",
    score = -abs(score)
  ) # force negative (left side)

c7 <- c7 |>
  rename(gene = !!gene_col, score = !!score_col, rank = !!rank_col) |>
  filter(gene %in% genes_c7) |>
  mutate(
    cluster = "CD16+ monocyte",
    score = abs(score)
  ) # force positive (right side)

plot_data <- bind_rows(c2, c7)

# --- Order genes: negative side (by score, most negative first) then positive side ---
gene_order <- c(
  c2 |> arrange(score) |> pull(gene),
  c7 |> arrange(desc(score)) |> pull(gene)
)
plot_data$gene <- factor(plot_data$gene, levels = rev(gene_order))

# --- Rank label position: just outside the bar tip ---
plot_data <- plot_data |>
  mutate(
    rank_label = paste("rank", rank),
    rank_hjust = ifelse(score < 0, 1.1, -0.1),
    rank_x = score + ifelse(score > 0, 0.02, -0.02),
    # gene name: sits right at x = 0, just inside the bar start
    gene_hjust = ifelse(score > 0, 1.05, -0.05)
  )

nature_palette <- c("Classical monocyte" = "#6BAA6E", "CD16+ monocyte" = "#5FA8A0")

p <- ggplot(plot_data, aes(x = score, y = gene, fill = cluster)) +
  geom_col(width = 0.7, color = NA) +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.3) +
  geom_text(aes(x = rank_x, label = rank_label, hjust = rank_hjust),
    size = 5.3 / .pt, color = "black"
  ) +
  geom_text(aes(x = 0, label = gene, hjust = gene_hjust),
    size = 5.3 / .pt, color = "black", fontface = "italic"
  ) +
  scale_fill_manual(values = nature_palette, name = NULL) +
  scale_x_continuous(
    limits = c(-0.65, 0.65),
    breaks = seq(-0.6, 0.6, 0.3)
  ) +
  labs(x = "Differential gene score\n(DC/CD16+ vs Classical monocyte)", y = NULL) +
  theme_minimal(base_size = 5.3) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(color = "black", size = 5.3),
    axis.title.x = element_text(size = 5.3),
    axis.title.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(color = "grey85", linewidth = 0.15),
    panel.border = element_blank(),
    axis.line.x = element_line(color = "black", linewidth = 0.3),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.background = element_blank(),
    legend.key.size = unit(2, "mm"),
    legend.text = element_text(size = 5.3),
    legend.spacing.x = unit(1, "mm"),
    legend.margin = margin(0, 0, 0, 0, unit = "mm"),
    legend.box.spacing = unit(0.5, "mm"),
    plot.margin = margin(1, 1, 1, 1, unit = "mm")
  )

ggsave("diverging_gene_score.pdf",
  plot = p,
  width = 50, height = 43, units = "mm", device = cairo_pdf
)


# ── FIGURE S18c ──────────────────────────────────────────────────────────────────────

# Example function to calculate Jaccard index between two character vectors
calculate_jaccard <- function(list_a, list_b) {
  intersection <- length(intersect(list_a, list_b))
  union <- length(union(list_a, list_b))
  if (union == 0) {
    return(0)
  }
  intersection / union
}

scores_path <- "pbmc_gene_ranked.csv"
scflame_markers <- read_csv(scores_path) |>
  dplyr::rename(cluster = cluster_k)

Idents(pbmc) <- "scflame_new"

# Run Seurat's marker discovery
# We use logfc.threshold = 0 and min.pct = 0 to make sure we don't truncate
# the lists too early before doing our top-N comparisons.
seurat_markers_raw <- FindAllMarkers(
  pbmc,
  features = unique(scflame_markers$gene),
  only.pos = TRUE,
  min.pct = 0.1, # Minimal filtering to speed up calculation
  logfc.threshold = 0.1,
  test.use = "wilcox"
)

# 4. Process Seurat outputs
seurat_markers <- seurat_markers_raw |>
  as_tibble() |>
  # Filter out unwanted gene families using regular expressions (case-insensitive)
  filter(
    !str_detect(gene, "(?i)^MT-"), # Mitochondrial genes
    !str_detect(gene, "(?i)^LINC"), # Long intergenic non-coding RNAs
    !str_detect(gene, "(?i)^CTD-"), # Clone/scaffold names
  ) |>
  group_by(cluster) |>
  arrange(p_val_adj, desc(avg_log2FC), .by_group = TRUE) |>
  ungroup() |>
  dplyr::select(cluster, gene) |>
  mutate(cluster = as.numeric(as.character(cluster)))

thresholds <- seq(10, 100, by = 10)
clusters <- unique(scflame_markers$cluster)

jaccard_results <- expand_grid(Cluster = clusters, N = thresholds) |>
  rowwise() |>
  mutate(
    Jaccard = {
      # Extract top N genes for this cluster from both methods
      genes_scflame <- scflame_markers |>
        filter(cluster == Cluster) |>
        head(N) |>
        pull(gene)

      genes_seurat <- seurat_markers |>
        filter(cluster == Cluster) |>
        head(N) |>
        pull(gene)

      calculate_jaccard(genes_scflame, genes_seurat)
    }
  ) |>
  ungroup()

rainbow_palette <- c(
  "0" = "#E31A1C",
  "1" = "#FF7F00",
  "2" = "#4D9221",
  "3" = "#006D2C",
  "4" = "#2B8CBE",
  "5" = "#08519C",
  "6" = "#6A3D9A",
  "7" = "#F768A1"
)

p <- ggplot(jaccard_results, aes(x = N, y = Jaccard, color = factor(Cluster), group = Cluster)) +
  geom_line(linewidth = 0.4, alpha = 0.85) +
  geom_point(size = 1, alpha = 0.9) +
  scale_color_manual(values = rainbow_palette) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.25)) +
  scale_x_continuous(breaks = c(10, 25, 50, 75, 100)) +
  labs(x = "Top N Genes Considered", y = "Jaccard Similarity Index", color = "Cluster") +
  guides(color = guide_legend(override.aes = list(linewidth = 0.4, size = 0.6))) +
  theme_bw(base_size = 5.3) +
  theme(
    panel.grid.major = element_line(color = "#E5E5E5", linewidth = 0.2),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(color = "#333333", linewidth = 0.3),
    axis.text = element_text(color = "#333333"),
    axis.title = element_text(face = "plain"),
    legend.title = element_text(face = "bold", size = 5.3),
    legend.text = element_text(size = 5.3),
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.key.size = unit(3, "mm"),
    legend.spacing.y = unit(0, "mm"),
    legend.spacing.x = unit(0.5, "mm"),
    legend.margin = margin(0, 0, 0, 0),
    plot.margin = margin(1, 1, 1, 1, "mm")
  )

ggsave("Supplementary_Fig_Jaccard_Benchmark.pdf", p, device = "pdf", width = 50, height = 36, units = "mm", dpi = 300)

# ── FIGURE S19A/B ──────────────────────────────────────────────────────────────────────

# ── config ────────────────────────────────────────────────────────────────────
scores_path <- "zeisel_gene_ranked.csv"
top_n <- 5 # top upregulated genes per cluster

KNOWN_MARKERS <- c(
  # Pyramidal CA1
  Spink8 = "Pyramidal CA1",
  Hpca = "Pyramidal CA1",
  Cpne6 = "Pyramidal CA1",
  Rgs14 = "Pyramidal CA1",
  Crym = "Pyramidal CA1",

  # Pyramidal SS
  Tbr1 = "Pyramidal SS",
  Mef2c = "Pyramidal SS",
  Nrn1 = "Pyramidal SS",
  Snap25 = "Pyramidal SS",
  Car10 = "Pyramidal SS",
  Camk2n1 = "Pyramidal SS",

  # Interneurons
  Gad1 = "Interneurons",
  Gad2 = "Interneurons",
  Slc32a1 = "Interneurons",
  Cnr1 = "Interneurons",
  Pnoc = "Interneurons",

  # Astrocytes
  Aqp4 = "Astrocytes",
  Slc1a3 = "Astrocytes",

  # Oligodendrocytes
  Mog = "Oligodendrocytes",
  Trf = "Oligodendrocytes",
  Plp1 = "Oligodendrocytes",
  Ermn = "Oligodendrocytes",

  # Mature Oligodendrocytes
  Gsn = "Mature Oligodendrocytes",
  Apod = "Mature Oligodendrocytes",
  Opalin = "Mature Oligodendrocytes",
  Mal = "Mature Oligodendrocytes",

  # Endothelial
  Gimap6 = "Endothelial",
  Ifitm3 = "Endothelial",
  Srgn = "Endothelial"
)

CELLTYPE_COLOURS <- c(
  "Oligodendrocytes" = "#4A90D9",
  "Pyramidal CA1" = "#E05A2B",
  "Endothelial" = "#52A552",
  "Interneurons" = "#9B6BB5",
  "Astrocytes" = "#56B4E9",
  "Pyramidal SS" = "#D4636B",
  "Mature Oligodendrocytes" = "#E8A838",
  "Other" = "grey88"
)

zeiselcounts <- read.csv("zeisel_rawcounts.csv", row.names = 1)
zeisel <- CreateSeuratObject(counts = t(zeiselcounts))
zeisel_truelabels <- read.csv("zeisel_clusters.csv")
true_labels <- base::as.factor(zeisel_truelabels$celltype)
zeisel$CellType <- zeisel_truelabels$celltype

# Normalize data
zeisel <- NormalizeData(zeisel)
zeisel <- FindVariableFeatures(zeisel)
zeisel <- ScaleData(zeisel)
zeisel <- RunPCA(zeisel)
zeisel <- FindNeighbors(zeisel, dims = 1:10)
zeisel <- FindClusters(zeisel, resolution = 0.8)
zeisel <- RunUMAP(zeisel, dims = 1:10)
zeisel <- RunTSNE(zeisel, dims = 1:30)

scflame_zeisel <- read.csv("scflame_alloc_eii_gmm_rep4.csv")
zeisel$scflame <- scflame_zeisel$cluster


# ── load and select top upregulated genes per cluster ─────────────────────────
df <- read_csv(scores_path, show_col_types = FALSE)
# Remove version suffix if present
df$gene <- sub("\\..*$", "", df$gene)

df_filtered <- df |>
  filter(
    !str_detect(gene, "(?i)^mt-|^mtrn"), # Mitochondrial (Case-insensitive)
    !str_detect(gene, "(?i)^rpl|^rps"), # Ribosomal proteins (Case-insensitive)
    !str_detect(gene, "^[a-zA-Z]{2,4}[0-9]+[a-zA-Z]+[0-9]*Rik$"), # Drops Riken transcripts (e.g., 4933409K07Rik)
    !str_detect(gene, "^Gm[0-9]"), # Drops predicted GenBank mouse models
    !str_detect(gene, "(?i)^hist"), # Histones (Case-insensitive)
    !str_detect(gene, "(?i)^al|^ac|^linc|^mir|^snord") # Non-coding RNAs / pseudogenes
  )

target_genes_list <- df_filtered |>
  group_by(cluster_k) |>
  slice_max(score, n = top_n, with_ties = FALSE) |>
  ungroup() |>
  distinct(gene) |>
  pull(gene)

row_order <- df_filtered |>
  group_by(cluster_k) |>
  slice_max(score, n = top_n, with_ties = FALSE) |>
  ungroup() |>
  plyr::arrange(as.numeric(as.character(cluster_k)), plyr::desc(score)) |>
  distinct(gene, .keep_all = TRUE) |>
  pull(gene)

score_mat <- df_filtered |>
  filter(gene %in% target_genes_list) |>
  dplyr::select(gene, cluster_k, score) |>
  pivot_wider(names_from = cluster_k, values_from = score) |>
  column_to_rownames("gene") |>
  as.matrix()


score_mat <- score_mat[, order(as.numeric(colnames(score_mat))), drop = FALSE]

score_mat <- score_mat[row_order[row_order %in% rownames(score_mat)], , drop = FALSE]

# ── annotations ───────────────────────────────────────────────────────────────
cell_type <- ifelse(
  rownames(score_mat) %in% names(KNOWN_MARKERS),
  KNOWN_MARKERS[rownames(score_mat)],
  "Other"
)

row_ann <- rowAnnotation(
  `Cell type` = cell_type,
  col = list(`Cell type` = CELLTYPE_COLOURS),
  simple_anno_size = unit(2, "mm"),
  annotation_name_gp = gpar(fontsize = 5.5, fontface = "bold"),
  annotation_name_side = "top",
  annotation_legend_param = list(
    `Cell type` = list(
      title_gp = gpar(fontsize = 5.8, fontface = "bold"),
      labels_gp = gpar(fontsize = 5.4),
      grid_height = unit(2, "mm"),
      grid_width = unit(2, "mm")
    )
  )
)

# ── colour scale ──────────────────────────────────────────────────────────────
col_fun <- colorRamp2(c(-1.5, 0, 1.5), c("#3B82C4", "white", "#C0392B"))

n_clusters <- ncol(score_mat)
n_genes <- nrow(score_mat)
ht_opt$TITLE_PADDING <- unit(1, "mm")

# ── heatmap ───────────────────────────────────────────────────────────────────
ht <- Heatmap(
  score_mat,
  name = "Gene score",
  col = col_fun,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = TRUE,
  column_labels = paste0("C", colnames(score_mat)),
  row_names_gp = gpar(
    fontsize = 5.4,
    fontface = ifelse(rownames(score_mat) %in% names(KNOWN_MARKERS),
      "bold.italic", "plain"
    )
  ),
  column_names_gp = gpar(fontsize = 5.4, fontface = "bold"),
  column_names_rot = 0,
  column_names_centered = TRUE,
  column_title = "Cluster",
  column_title_side = "bottom",
  column_title_gp = gpar(fontsize = 5.8, fontface = "bold"),
  row_title = NULL,
  right_annotation = row_ann,
  border = TRUE,
  border_gp = gpar(lwd = 0.6),
  row_gap = unit(0, "mm"),
  column_gap = unit(0, "mm"),
  width = unit(21, "mm"),
  height = unit(79, "mm"),
  heatmap_legend_param = list(
    title_gp      = gpar(fontsize = 5.8, fontface = "bold"),
    labels_gp     = gpar(fontsize = 5.5),
    legend_height = unit(18, "mm"),
    grid_width    = unit(2, "mm"),
    border        = "grey40"
  )
)


pdf("figure_b_heatmap_zeisel.pdf",
  width  = 3.2,
  height = 4.2
)
draw(ht, padding = unit(c(1, 1, 1, 1), "mm"))

DotPlot(
  object   = zeisel,
  features = row_order, # use row_order directly, already correctly ordered
  group.by = "scflame"
)

features <- target_genes_list

dot_data <- DotPlot(
  object   = zeisel,
  features = row_order,
  group.by = "scflame"
)$data

dot_data$features.plot <- factor(dot_data$features.plot, levels = rev(row_order))

# Build the dot plot ─────────────────────────────────────────────────────
dp <- ggplot(dot_data, aes(
  x = id,
  y = features.plot,
  size = pct.exp,
  color = avg.exp.scaled
)) +
  geom_point(shape = 16) +
  scale_size(range = c(0, 2), name = "% expressed") +
  scale_color_gradient(low = "grey90", high = "#88419F", name = "Avg expression") +
  scale_x_discrete(labels = paste0("C", levels(factor(dot_data$id)))) +
  scale_y_discrete(expand = c(0, 0.5)) +
  theme_bw(base_size = 6) +
  theme(
    axis.text.x = element_text(size = 5.4, colour = "black", face = "bold", angle = 0, hjust = 0.5),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title = element_blank(),
    panel.grid.major = element_line(colour = "white", linewidth = 0),
    panel.border = element_rect(colour = "black", linewidth = 0.5),
    legend.key.size = unit(3, "mm"),
    legend.text = element_text(size = 5.5),
    legend.title = element_text(size = 5.5, face = "bold"),
    legend.position = "left"
  ) +
  labs(x = "Cluster", y = NULL) +
  force_panelsizes(rows = unit(80, "mm"))


ggsave("figa_dotplot_zeisel.pdf", dp, dpi = 300, width = 45, height = 90, units = "mm")

# ── FIGURE S19C ──────────────────────────────────────────────────────────────────────

df <- read_csv("zeisel_gene_scores_top50.csv", show_col_types = FALSE)

cluster_labels <- c(
  "0" = "C0: Pyramidal CA1",
  "1" = "C1: Astrocytes",
  "2" = "C2: Oligodendrocytes 1",
  "3" = "C3: Endothelial",
  "4" = "C4: Pyramidal SS",
  "5" = "C5: Oligodendrocytes 2",
  "6" = "C6: Interneurons"
)

# Run Pathway Enrichment
run_enrichment <- function(k, data) {
  # Get top 50 genes for this cluster
  genes <- data |>
    filter(cluster_k == k, score > 0) |>
    slice_max(score, n = 50) |>
    pull(gene)

  # Run Gene Ontology (Biological Process) enrichment
  res <- enrichGO(
    gene          = genes,
    OrgDb         = org.Mm.eg.db,
    keyType       = "SYMBOL",
    ont           = "BP", # Biological Process
    pAdjustMethod = "BH", # Benjamini-Hochberg FDR
    pvalueCutoff  = 0.05,
    qvalueCutoff  = 0.2
  )

  if (is.null(res) || nrow(res@result) == 0) {
    return(NULL)
  }

  # Add cluster ID to results
  res@result |> mutate(cluster_k = as.character(k))
}

# Apply across all clusters and combine
message("Running Pathway Enrichment... (This may take a minute)")
enrich_res <- map_dfr(names(cluster_labels), ~ run_enrichment(.x, df))

# Prepare data for plotting
plot_data <- enrich_res |>
  filter(p.adjust < 0.05) |> # Keep only significant pathways
  group_by(cluster_k) |>
  slice_min(p.adjust, n = 3, with_ties = FALSE) |> # Top 4 pathways per cluster
  ungroup() |>
  dplyr::mutate(
    # Convert "10/50" GeneRatio string to a numeric decimal (0.2)
    GeneRatio_num = sapply(strsplit(GeneRatio, "/"), function(x) as.numeric(x[1]) / as.numeric(x[2])),
    # Calculate -log10(FDR)
    `-log10(FDR)` = -log10(p.adjust),
    # Map biological names to clusters
    Cluster_Name = cluster_labels[cluster_k],
    # Clean up overly long GO terms
    Description = str_wrap(Description, width = 45)
  ) |>
  # Order the y-axis pathways so they group nicely by cluster
  plyr::arrange(cluster_k, p.adjust) |>
  dplyr::mutate(Description = factor(Description, levels = unique(Description)))

# Order the x-axis properly
plot_data$Cluster_Name <- factor(plot_data$Cluster_Name, levels = cluster_labels)

# Generate Dot Plot
p <- ggplot(plot_data, aes(x = Cluster_Name, y = Description)) +
  geom_point(aes(size = GeneRatio_num, fill = `-log10(FDR)`),
    shape = 21, stroke = 0.2, color = "black"
  ) +
  scale_fill_viridis(option = "plasma", direction = -1, name = expression(-log[10](FDR))) +
  scale_size_continuous(range = c(0.8, 2.8), name = "Gene Ratio") +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = 5.2, base_family = "Helvetica") +
  theme(
    axis.text.x = element_text(
      angle = 45, hjust = 1, vjust = 1, color = "black",
      face = "bold", size = 5.2
    ),
    axis.text.y = element_text(color = "black", size = 5.2),
    axis.title = element_text(size = 5.2),
    panel.grid.major.x = element_line(color = "grey90", linetype = "dashed", linewidth = 0.15),
    panel.grid.major.y = element_line(color = "grey90", linetype = "dotted", linewidth = 0.15),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.3),
    legend.position = "right",
    legend.title = element_text(face = "bold", size = 5.2),
    legend.text = element_text(size = 5.2),
    legend.key.size = unit(2.5, "mm"),
    legend.spacing.y = unit(0.5, "mm"),
    legend.box.spacing = unit(1, "mm"),
    plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "mm")
  )

# Save
ggsave("ORA_enrichment_zeisel.pdf",
  plot = p,
  width = 80, height = 77, units = "mm", device = cairo_pdf
)

# ── FIGURE S21 ──────────────────────────────────────────────────────────────────────

input_ranked_csv <- "zeisel_gene_ranked.csv"
top_n_paths <- 3


message("Loading pre-computed data...")
df_ranked <- read_csv(input_ranked_csv, show_col_types = FALSE)

target_clusters <- c("0", "1", "2", "3", "4", "5", "6")

cluster_labels <- c(
  "0" = "C0: Pyramidal CA1",
  "1" = "C1: Astrocytes",
  "2" = "C2: Oligodendrocytes 1",
  "3" = "C3: Endothelial",
  "4" = "C4: Pyramidal SS",
  "5" = "C5: Oligodendrocytes 2",
  "6" = "C6: Interneurons"
)

message("Fetching MSigDB Pathways...")
m_df <- msigdbr(
  species = "Mus musculus",
  category = "M2",
  subcollection = "REACTOME",
  db_species = "MM"
)
pathways_list <- split(m_df$gene_symbol, m_df$gs_name)

run_cluster_fgsea <- function(k, data, pathways) {
  cluster_data <- data |>
    filter(cluster_k == as.numeric(k)) |>
    arrange(desc(score))

  ranks <- setNames(cluster_data$score, cluster_data$gene)

  fgsea_res <- fgseaMultilevel(
    pathways = pathways, stats = ranks,
    minSize = 10, maxSize = 500, eps = 0
  )

  if (is.null(fgsea_res) || nrow(fgsea_res) == 0) {
    return(NULL)
  }
  fgsea_res |>
    as_tibble() |>
    mutate(cluster_k = as.character(k))
}

all_gsea_results <- map_dfr(c(0:6), ~ run_cluster_fgsea(.x, df_ranked, pathways_list))
all_res <- all_gsea_results

run_cluster_gsea_cp <- function(k, data) {
  ranks <- data |>
    dplyr::filter(cluster_k == as.numeric(k)) |>
    dplyr::arrange(dplyr::desc(score)) |>
    (\(x) stats::setNames(x$score, x$gene))()

  term2gene <- m_df |>
    dplyr::select(gs_name, gene_symbol)

  clusterProfiler::GSEA(
    geneList      = ranks,
    TERM2GENE     = term2gene,
    minGSSize     = 10,
    maxGSSize     = 500,
    pvalueCutoff  = 1,
    eps           = 0,
    seed          = TRUE,
    pAdjustMethod = "BH"
  )
}

gsea_objects <- purrr::map(c(0:6), ~ run_cluster_gsea_cp(.x, df_ranked))
names(gsea_objects) <- target_clusters


plot_gsea_clean <- function(res, top_ids, title,
                            colors = c("#9970AB", "#D95F02", "#1B9E77")) {
  colors <- colors[seq_along(top_ids)]

  gsdata <- do.call(rbind, lapply(seq_along(top_ids), function(i) {
    enrichplot:::gsInfo(res, top_ids[i]) |>
      mutate(pathway = top_ids[i], color = colors[i])
  }))

  label_map <- setNames(
    str_trunc(str_replace(top_ids, "GSE[0-9]+_", ""), 45, ellipsis = "…"),
    top_ids
  )
  gsdata$label <- label_map[gsdata$pathway]

  # ── Panel 1: Running ES curve ──────────────────────────────────────────────
  p1 <- ggplot(gsdata, aes(x = x, y = runningScore, colour = label)) +
    geom_hline(yintercept = 0, linewidth = 0.25, colour = "grey50", linetype = "dashed") +
    geom_line(linewidth = 0.4) +
    scale_colour_manual(values = setNames(colors, label_map[top_ids])) +
    scale_x_continuous(expand = c(0.01, 0)) +
    labs(x = NULL, y = "Running Enrichment Score", title = title, colour = NULL) +
    theme_classic(base_size = 5.8) +
    theme(
      plot.title = element_text(size = 5.8, face = "bold"),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.line.x = element_blank(),
      axis.title.y = element_text(size = 5.8),
      axis.text.y = element_text(size = 5.8),
      legend.position = c(1.03, 1.08),
      legend.justification = c(1, 1),
      legend.text = element_text(size = 5),
      legend.key.height = unit(1.5, "mm"),
      legend.key.width = unit(3, "mm"),
      legend.background = element_blank(),
      plot.margin = margin(2, 2, 0, 2)
    )

  # ── Panel 2: Barcode ───────────────────────────────────────────────────────
  n <- length(top_ids)
  barcode_data <- do.call(rbind, lapply(seq_along(top_ids), function(i) {
    d <- enrichplot:::gsInfo(res, top_ids[i])
    d |>
      filter(position == 1) |>
      mutate(
        pathway = top_ids[i],
        label   = label_map[top_ids[i]],
        ymin    = (i - 1) / n,
        ymax    = i / n - 0.05,
        color   = colors[i]
      )
  }))

  p2 <- ggplot(barcode_data, aes(
    x = x, xend = x,
    y = ymin, yend = ymax,
    colour = label
  )) +
    geom_segment(linewidth = 0.15) +
    scale_colour_manual(values = setNames(colors, label_map[top_ids])) +
    scale_x_continuous(expand = c(0.01, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(x = "Gene Rank", y = NULL) +
    theme_classic(base_size = 5.8) +
    theme(
      axis.text.y       = element_blank(),
      axis.ticks.y      = element_blank(),
      axis.line.y       = element_blank(),
      axis.text.x       = element_text(size = 5.5),
      axis.title.x      = element_text(size = 5.5),
      legend.position   = "none",
      plot.margin       = margin(0, 2, 2, 2)
    )

  p1 / p2 + plot_layout(heights = c(4, 1))
}

plots_clean <- imap(gsea_objects, function(res, k) {
  cluster_idx <- as.numeric(k)

  top_ids <- res@result |>
    filter(p.adjust < 0.05, NES > 0) |>
    arrange(desc(abs(NES))) |>
    slice_head(n = top_n_paths) |>
    pull(ID)

  if (length(top_ids) == 0) {
    message("No significant paths for cluster ", k)
    return(NULL)
  }

  plot_gsea_clean(res, top_ids, title = cluster_labels[cluster_idx + 1])
})

c0 <- plots_clean[1][[1]]
c1 <- plots_clean[2][[1]]
c2 <- plots_clean[3][[1]]
c3 <- plots_clean[4][[1]]
c4 <- plots_clean[5][[1]]
c5 <- plots_clean[6][[1]]
c6 <- plots_clean[7][[1]]

mountains_extra <- plot_grid(c0, c1, c2, c3, c4, c5, c6, ncol = 2)

ggsave("Mountains_zeisel.pdf", mountains_extra, width = 150, height = 170, units = "mm", dpi = 300)